### 환경 변수
@base = {{host}}/api/v1/auth

### sys 회원가입
POST {{base}}/signup/sys
Content-Type: application/json

{
  "loginEmail": "sys1@naver.com",
  "password": "123456",
  "empNo": "DF123",
  "name": "sys1",
  "phone": "010-1234-5678",
  "departmentId": 2,
  "positionId": 2,
  "companyId": 1
}
### admin 회원가입
POST {{base}}/signup/admin
Content-Type: application/json

{
  "loginEmail": "admin1@naver.com",
  "password": "123456",
  "empNo": "AD123",
  "name": "admin1",
  "phone": "010-3322-5678",
  "departmentId": 3,
  "positionId": 3,
  "companyId": 2
}

### user 회원가입
POST {{base}}/signup/user
Content-Type: application/json

{
  "loginEmail": "user1@naver.com",
  "password": "123456",
  "empNo": "US123",
  "name": "user1",
  "phone": "010-1122-5678",
  "departmentId": 3,
  "positionId": 3,
  "companyId": 2
}

### SYS 로그인
POST {{base}}/login
Content-Type: application/json

{
  "loginEmail": "sys1@naver.com",
  "password": "123456"
}

### ADMIN 로그인
POST {{base}}/login
Content-Type: application/json

{
  "loginEmail": "admin1@naver.com",
  "password": "123456"
}

### USER 로그인
POST {{base}}/login
Content-Type: application/json

{
  "loginEmail": "user1@naver.com",
  "password": "123456"
}
