### 환경 변수
@base = {{host}}/auth

### ADMIN 회원가입
POST {{base}}/signup/admin
Content-Type: application/json

{
  "loginEmail": "admin4@naver.com",
  "password": "123456",
  "empNo": "AD456",
  "name": "admin4",
  "phone": "010-4444-4444",
  "departmentId": 3,
  "positionId": 4
}

### ADMIN 로그인
POST {{base}}/login
Content-Type: application/json

{
  "loginEmail": "admin4@naver.com",
  "password": "123456"
}

### USER 로그인
POST {{base}}/login
Content-Type: application/json

{
  "loginEmail": "user1@naver.com",
  "password": "123456"
}
