### 환경 변수
@base = {{host}}/api/v1/sys/company
@token = Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJlMjk4ODIwZDE3MGU0NWMyYWVhMWFhODk0ZDJkOThjMyIsInJvbGUiOiJST0xFX1NZUyIsImlhdCI6MTc1ODE1MzgxMywiZXhwIjoxNzU4MTg5ODEzLCJ0ZW5hbnRfaWQiOjIsImVtcGxveWVlX3V1aWQiOiJlMjk4ODIwZDE3MGU0NWMyYWVhMWFhODk0ZDJkOThjMyIsImVtcGxveWVlX25hbWUiOiJzeXMyIn0.66qaf25aTQu8B_GCkarryMJ87uEcE3M9e1D2jF7QT2M

### 회사 생성
POST {{base}}
Authorization: {{token}}
Content-Type: application/json

{
  "name": "테스트회사3",
  "bizNo": "333-22-22222",
  "address": "서울 강남동",
  "phone": "010-3333-1111"
}

### 1개 회사 조회
GET {{base}}/5
Authorization: {{token}}
Content-Type: application/json

###  여러개 회사 조회 (페이징, 검색 조건)
GET {{base}}
Authorization: {{token}}
Content-Type: application/json

{
  "page": 0,
  "size": 10
}

### 회사 수정
PUT {{base}}/6
Authorization: {{token}}
Content-Type: application/json

{
  "name": "테스트회사수정1",
  "bizNo": "432-22-22222",
  "address": "서울 구로동",
  "phone": "010-1131-1111"
}


### 회사 삭제(연관 데이터 존재시 삭제 안됨)
DELETE {{base}}/6
Authorization: {{token}}
Content-Type: application/json
