### 환경 변수
@base = {{host}}/api/v1/user/item
@token = Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIyZDhlYjc4NzI1Yjk0MzNmOGY4MTI2MTc0YjczYTI2OCIsInJvbGUiOiJST0xFX0FETUlOIiwiaWF0IjoxNzU2OTc3NjcyLCJleHAiOjE3NTcwMTM2NzIsInRlbmFudF9pZCI6Mn0.be0NjKc-CytVgLT6CvJZToUrfE-VPiPeYxXe9MEpElA

### 품목 등록
POST {{base}}
Authorization: {{token}}
Content-Type: application/json
Accept: application/json

{
  "name": "책상",
  "code": "ITM-0003",
  "price": 320000,
  "unit": "개",
  "category": "MERCHANDISE"
}

### 품목 상세 조회 (여기 123을 실제 item_id로 바꿔서 사용)
GET {{base}}/1
Authorization: {{token}}
Accept: application/json

### 품목 목록 조회 (이름+카테고리 검색, 페이징)
GET {{base}}
Authorization: {{token}}
Content-Type: application/json
Accept: application/json

{
  "page": 0,
  "size": 20,
  "name": "펜",
  "category": "MERCHANDISE"
}

### 품목 목록 조회 (이름만 검색)
GET {{base}}
Authorization: {{token}}
Content-Type: application/json
Accept: application/json

{
  "page": 0,
  "size": 10,
  "name": "볼"
}

### 품목 목록 조회 (카테고리만 검색)
GET {{base}}
Authorization: {{token}}
Content-Type: application/json
Accept: application/json

{
  "page": 1,
  "size": 10,
  "category": "CONSUMABLE"
}

### 품목 수정 (전체 수정: PUT) - 123을 실제 item_id로 교체
PUT {{base}}/1
Authorization: {{token}}
Content-Type: application/json
Accept: application/json

{
  "name": "프리미엄 볼펜",
  "code": "ITM-0001-PRM",
  "price": 1500,
  "unit": "EA",
  "category": "MERCHANDISE"
}

### 품목 소프트 삭제 - 123을 실제 item_id로 교체
DELETE {{base}}/1
Authorization: {{token}}
Accept: application/json
