@base = {{host}}/admin/position

### 직급 생성
POST {{base}}
Authorization: {{token}}
Content-Type: application/json
Accept: application/json

{
  "name": "CEO"
}

### 직급 목록 조회 (level_no 오름차순)
GET {{base}}
Authorization: {{token}}
Accept: application/json

### 직급 이름 수정
PUT {{base}}/5/name
Authorization: {{token}}
Content-Type: application/json
Accept: application/json

{
  "name": "차장"
}

### 직급 순서 변경
PUT {{base}}/14/level-no
Authorization: {{token}}
Content-Type: application/json
Accept: application/json

{
  "levelNo": 3
}

### 직급 삭제
DELETE {{base}}/14
Authorization: {{token}}
Accept: application/json
