FROM maven:3.9-eclipse-temurin-17 AS dev
WORKDIR /app

COPY pom.xml .
RUN mvn -q -e -DskipTests dependency:go-offline

COPY src ./src

# application 을 compose.yml 에서 지정한 걸로 실행
CMD ["mvn","-q","-Dspring-boot.run.fork=false","-Dspring-boot.run.jvmArguments=-Dspring.devtools.restart.poll-interval=2s -Dspring.devtools.restart.quiet-period=1s","spring-boot:run"]