@base = {{host}}/api/v1/user/report/stock/5/movement
@token = Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIwNzM5MjZjYTgxNmY0ODY1YTVmMDU2YWFhMGJlOWJmMyIsInJvbGUiOiJST0xFX1VTRVIiLCJpYXQiOjE3NTc5MDA3MzAsImV4cCI6MTc1NzkzNjczMCwidGVuYW50X2lkIjoyfQ.fSRP8liK3WlO-5eF_7YnWIs3-XCyLDQ1OkyI2d8wkMQ

### 재고 변동 내역 조회(팝업)
GET {{base}}
Authorization: {{token}}
Content-Type: application/json

{
  "period": "ALL",
  "status": "ALL",
  "page": 0,
  "size": 20
}
